### ISSUE TITLE
Inconsistent BatchSize

### ISSUE THREAD

**Issue by HMJiangGatech** [google/airdialogue_model#8]
https://github.com/google/airdialogue_model/blob/5bdc7996a6dd27c5f31c4ff5d4fd092a1d17a599/self_play.py#L132-L144

In line 144, we should replace `batch_size` by `end_ind-start_ind`. Otherwise, there will be an inconsistent batchsize issue in the last iteration.

**Comment by josephch405** [comment]
This will be fixed in #6

**Comment by josephch405** [comment]
Address in #10
